# codecov.yml
#
# codecov Code Coverage definitions
# See https://docs.codecov.com/docs/codecov-yaml
#
# yaml-language-server: $schema=https://json.schemastore.org/codecov
#
# Validate this file with command:
#     curl --data-binary @.github/codecov.yml https://codecov.io/validate
# or
#     tools/codecov-validate.sh
---
codecov:
  bot: "codecov-io"
  max_report_age: 24
  disable_default_path_fixes: false
  require_ci_to_pass: true
  notify:
    after_n_builds: 1
    wait_for_ci: true
coverage:
  # see https://docs.codecov.com/docs/commit-status
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        paths:
          - "src"
        branches:
          - main
          - codecov
    patch:
      default:
        informational: true
...
