# Cargo.toml

[package]
name = "super_speedy_syslog_searcher"
description = "Super Speedy Syslog Searcher will search syslog files and sort entries by datetime. DateTime filters may be passed to narrow the search. It aims to be very fast."
version = "0.0.36"
edition = "2021"
rust-version = "1.62"
repository = "https://github.com/jtmoon79/super-speedy-syslog-searcher"
authors = ["James Thomas Moon"]
license = "MIT"
keywords = ["syslog", "search", "sort"]
readme = "README.md"
# Do not set metadata fields `documentation` or `homepage` unless using
# non-standard websites.
# See <https://rust-lang.github.io/api-guidelines/documentation.html#cargotoml-includes-all-common-metadata-c-metadata>
exclude = [
    ".github/*",
    "benches/bench_prints.rs",
    "benches/bench_ranges.rs",
    "benches/bench_syslinereader.rs",
    "benches/README.md",
    "logs/*",
    "src/**/README.md",
    "tools/*",
    "tests/*",
    "rustfmt.toml",
]

[dependencies]
arrayref = "0.3.6"
backtrace = "0.3.66"
chrono = "0.4.22"
clap = { version = "3.2.22", features = ["derive"] }
const_format = "0.2.28"
const-str = "0.5.1"
crossbeam-channel = "0.5.6"
encoding_rs = "0.8.31"
flate2 = "1.0.24"
itertools = "0.10.5"
lazy_static = "1.4.0"
lru = "0.8.1"
lzma-rs = "0.2.0"
mime_guess = "2.0.4"
more-asserts = "0.3.1"
mut_static = "5.0.0"
rand = "0.8.5"
rangemap = "1.0.3"
regex = "1.6.0"
static_assertions = "1.1.0"
si_trace_print = "0.2.5"
tar = "0.4.38"
termcolor = "1.1.3"
unicode-width = "0.1.10"
unroll = "0.1.5"
walkdir = "2.3.2"

[lib]
name = "s4lib"
path = "src/lib.rs"
crate-type = ["lib"]
edition = "2021"
test = true
doc = true
doctest = true
bench = false
#plugin = false
#proc-macro = false
#harness = false

[[bin]]
name = "s4"
path = "src/bin/bin.rs"
edition = "2021"
test = true
doc = true
bench = false

[dev-dependencies]
arraystring = "0.3.0"
bstr = "1.0.1"
criterion = "0.4.0"
flamegraph = "0.6.2"
jetscii = "0.5.3"
memchr = "2.5.0"
tempfile = "3.3.0"
test-case = "2.2.2"

# other helpful development tools
# cargo install --locked cargo-expand cargo-nextest

[[bench]]
name = "bench_decode_utf"
harness = false

[[bench]]
name = "bench_slice_contains"
harness = false
