# Cargo.toml

[package]
name = "super_speedy_syslog_searcher"
description = "A super speedy syslog searcher!"
version = "0.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# enabled for flamegraph (https://github.com/flamegraph-rs/flamegraph#usage-with-benchmarks)
#[profile.bench]
#debug = true
#[profile.release]
#debug = true

[dev-dependencies]
flamegraph = "0.6.1"

[dependencies]
atty = "0.2.14"
backtrace = "0.3.64"
chain-cmp =  "0.2.0"
chrono = "0.4.19"
clap = { version = "3.1.7", features = ["derive"] }
crossbeam-channel = "0.5.4"
debug_print = "1.0.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
lru = "0.7.3"
more-asserts = "0.2.2"
rand = "0.8.5"
rangemap = "1.0.1"
rayon = "1.5.1"
mut_static = "5.0.0"
tempfile = "3.3.0"
termcolor = "1.1.3"
