# Cargo.toml

[package]
name = "super_speedy_syslog_searcher"
description = "Super Speedy Syslog Searcher will search syslog files and sort entries by datetime. DateTime filters may be passed to narrow the search. It aims to be very fast."
version = "0.0.26"
edition = "2021"
repository = "https://github.com/jtmoon79/super-speedy-syslog-searcher"
authors = ["James Thomas Moon"]
license = "MIT"
keywords = ["syslog", "search", "sort"]
readme = "README.md"
rust-version = "1.61"
# Do not set metadata fields `documentation` or `homepage` unless using
# non-standard websites.
# See <https://rust-lang.github.io/api-guidelines/documentation.html#cargotoml-includes-all-common-metadata-c-metadata>

[dependencies]
arrayref = "0.3.6"
backtrace = "0.3.65"
chrono = "0.4.19"
clap = { version = "3.2.15", features = ["derive"] }
const_format = "0.2.25"
const-str = "0.4.3"
crossbeam-channel = "0.5.5"
encoding_rs = "0.8.31"
flate2 = "1.0.24"
itertools = "0.10.3"
lazy_static = "1.4.0"
lru = "0.7.7"
lzma-rs = "0.2.0"
mime_guess = "2.0.4"
more-asserts = "0.2.2"
mut_static = "5.0.0"
rand = "0.8.5"
rangemap = "1.0.3"
regex = "1.5.6"
static_assertions = "1.1.0"
tar = "0.4.38"
termcolor = "1.1.3"
unicode-width = "0.1.9"
unroll = "0.1.5"
walkdir = "2.3.2"

[lib]
name = "s4lib"
path = "src/lib.rs"
crate-type = ["lib"]
edition = "2021"
test = true
doctest = false
#bench = false
#doc = false
#plugin = false
#proc-macro = false
#harness = false

[[bin]]
name = "s4"
path = "src/bin/bin.rs"
test = true
doc = false
edition = "2021"

[dev-dependencies]
arraystring = "0.3.0"
bstr = "0.2.17"
criterion = "0.3.5"
flamegraph = "0.6.1"
jetscii = "0.5.1"
memchr = "2.4.1"
tempfile = "3.3.0"
test-case = "2.2.1"

# other helpful tools
# cargo install --locked cargo-expand cargo-nextest

[[bench]]
name = "bench_decode_utf"
harness = false

[[bench]]
name = "bench_slice_contains"
harness = false

[[bench]]
name = "bench_syslinereader"
harness = false
