# Cargo.toml

[package]
name = "super_speedy_syslog_searcher"
description = "A super speedy syslog searcher!"
version = "0.0.16"
edition = "2021"
homepage = "https://github.com/jtmoon79/super-speedy-syslog-searcher"
repository = "https://github.com/jtmoon79/super-speedy-syslog-searcher"
documentation = "https://github.com/jtmoon79/super-speedy-syslog-searcher"
authors = ["James Thomas Moon"]
license = "MIT"
keywords = ["syslog", "search", "sort"]
readme = "README.md"
rust-version = "1.61"

[dev-dependencies]
arraystring = "0.3.0"
bstr = "0.2.17"
criterion = "0.3.5"
flamegraph = "0.6.1"
jetscii = "0.5.1"
memchr = "2.4.1"

[[bench]]
name = "bench_decode_utf"
harness = false

[[bench]]
name = "bench_slice_contains"
harness = false

[dependencies]
arrayref = "0.3.6"
backtrace = "0.3.65"
chain-cmp =  "0.2.0"
chrono = "0.4.19"
clap = { version = "3.1.17", features = ["derive"] }
crossbeam-channel = "0.5.4"
debug_print = "1.0.0"
encoding_rs = "0.8.31"
flate2 = "1.0.24"
itertools = "0.10.3"
lazy_static = "1.4.0"
lru = "0.7.5"
mime = "0.3.16"
mime_guess = "2.0.4"
mime-sniffer = "0.1.2"
more-asserts = "0.2.2"
mut_static = "5.0.0"
rand = "0.8.5"
rangemap = "1.0.1"
static_assertions = "1.1.0"
tempfile = "3.3.0"
termcolor = "1.1.3"
unicode-width = "0.1.9"
unroll = "0.1.5"
walkdir = "2.3.2"

[[bin]]
name = "s4"
path = "src/main.rs"
test = true
doc = true
