---
name: Rust
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Debug
        run: cargo build --verbose
      - name: Build Release
        run: cargo build --release --verbose
      - name: Build Bench
        run: cargo bench --no-run
      - name: Run Tests
        run: cargo test -j1 --verbose -- --test-threads=1
