---
name: Rust
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  S4_TEST_FILES: ./logs/other/tests/dtf2-2.log
                 ./logs/other/tests/dtf3-2a.log
                 ./logs/other/tests/dtf5-6a.log.gz
jobs:
  job_build_debug_release_test:
    runs-on: ubuntu-latest
    steps:
      # build & upload debug
      - uses: actions/checkout@v2
      - name: Build Debug
        run: |
          set -eux
          cargo build --verbose
          cp -av ./target/debug/s4 ./s4_debug
      - name: Upload debug binary
        uses: actions/upload-artifact@v3
        with:
          name: s4_debug
          path: ./s4_debug
      # build & upload release
      - name: Build Release
        run: |
          set -eux
          cargo build --release --verbose
          cp -av ./target/release/s4 ./s4_release
      - name: Upload release binary
        uses: actions/upload-artifact@v3
        with:
          name: s4_release
          path: ./s4_release
      # bench sanity check, do not run them
      #- name: Bench
      #  run: cargo bench --no-run
      # tests
      - name: Run Tests
        run: cargo test -j1 --verbose -- --test-threads=1
  job_runs:
    needs: job_build_debug_release_test
    runs-on: ubuntu-latest
    steps:
      # checkout for the log files
      - uses: actions/checkout@v2
      # download & run debug
      - name: Download debug binary
        uses: actions/download-artifact@v3
        with:
          name: s4_debug
      - name: Run Program Debug
        run: |
          set -eux
          PROGRAM=./s4_debug
          chmod -v +x ${PROGRAM}
          ${PROGRAM} --help
          ${PROGRAM} --color=never $S4_TEST_FILES
          ${PROGRAM} --color=never -l -s -n -w $S4_TEST_FILES
          ${PROGRAM} --color=never -l -s -p -w $S4_TEST_FILES
          ${PROGRAM} --color=never -u -s -n -w $S4_TEST_FILES
          ${PROGRAM} --color=never -u -s -p -w $S4_TEST_FILES
          ${PROGRAM} --color=always -l -s -n -w $S4_TEST_FILES
          ${PROGRAM} --color=always -l -s -p -w $S4_TEST_FILES
          ${PROGRAM} --color=always -u -s -n -w $S4_TEST_FILES
          ${PROGRAM} --color=always -u -s -p -w $S4_TEST_FILES
      # download & run release
      - name: Download release binary
        uses: actions/download-artifact@v3
        with:
          name: s4_release
      - name: Run Program Release
        run: |
          set -eux
          PROGRAM=./s4_release
          chmod -v +x ${PROGRAM}
          ${PROGRAM} --help
          ${PROGRAM} --color=never $S4_TEST_FILES
          ${PROGRAM} --color=never -l -s -n -w $S4_TEST_FILES
          ${PROGRAM} --color=never -l -s -p -w $S4_TEST_FILES
          ${PROGRAM} --color=never -u -s -n -w $S4_TEST_FILES
          ${PROGRAM} --color=never -u -s -p -w $S4_TEST_FILES
          ${PROGRAM} --color=always -l -s -n -w $S4_TEST_FILES
          ${PROGRAM} --color=always -l -s -p -w $S4_TEST_FILES
          ${PROGRAM} --color=always -u -s -n -w $S4_TEST_FILES
          ${PROGRAM} --color=always -u -s -p -w $S4_TEST_FILES
      - name: Run Script compare-grep-sort
        run: |
          set -eux
          export PROGRAM=./s4_release
          SCRIPT=./tools/compare-grep-sort1.sh
          chmod -v +x "${PROGRAM}" "${SCRIPT}"
          "${SCRIPT}"
